spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/affordable-automation}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:hunter}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  pathsToMatch: /api/**
stripe:
  api:
    key:
      key=your_secret_key_here:pk_live_51MsqEFHeIlY7KZMg3kDSxAYrpuUliUal93C1EkJdwnRk4aQyxpxzWzDOMgVu0ZPcbisjz9tWR3Yln5Il63o4jL3d00uVAynC5V
